[package]
name = "pretty"
version = "0.0.0"
edition = "2021"

[dependencies]
arena = { path = "../arena" }
hir = { path = "../hir" }
thir = { path = "../thir" }
verde = { path = "../verde" }

pretty = "0.12.3"
