[package]
name = "yamc"
version = "0.1.0"
edition = "2021"

[dependencies]
diag = { path = "diag" }
name_resolve = { path = "name_resolve" }
parse = { path = "parse" }

clap = { version = "3.1", features = ["derive"] }

[workspace]
members = [
    "diag",
    "name_resolve",
    "parse",
]

[profile.release]
debug = true

[profile.dev.package.parse]
opt-level = 3
