[workspace]
members = [
#    "compiler/yamc",

    "compiler/common/diag",
    "compiler/common/intern",

    "compiler/syntax/ast",
    "compiler/syntax/lex",
    "compiler/syntax/parse",
    "compiler/syntax/syntax",
]

[profile.release]
debug = true
