[workspace]
members = [
    "ast",
#    "codegen",
    "diag",
#    "hir",
#    "id",
    "intern",
    "lex",
    "parse",
#    "ssir",
    "syntax",
#    "tyck",
]

[profile.release]
debug = true

[profile.dev.package.parse]
opt-level = 3
