[workspace]
members = ["compiler/*", "compiler/verde/derive"]
exclude = ["compiler/driver", "compiler/hir", "compiler/hir-lower", "compiler/yamc", "compiler/yamw"]

resolver = "2"

[profile.release]
debug = true
