[package]
name = "yamc"
version = "0.1.0"
edition = "2021"

[dependencies]
yamd = { path = "yamd" }
yamp = { path = "yamp" }

clap = { version = "3.1", features = ["derive"] }
lasso = { version = "0.6", features = ["ahash"] }

[workspace]
members = [
    "yamd",
    "yamp",
]
