[workspace]
members = [
    "compiler/ast",
#    "codegen",
    "compiler/diag",
#    "hir",
#    "id",
    "compiler/intern",
    "compiler/lex",
    "compiler/parse",
#    "ssir",
    "compiler/syntax",
#    "tyck",
]

[profile.release]
debug = true

[profile.dev.package.parse]
opt-level = 3
