[package]
name = "yamc"
version = "0.1.0"
edition = "2021"

[dependencies]
diag = { path = "diag" }
name_resolve = { path = "name_resolve" }
parse = { path = "parse" }
# type_check = { path = "type_check" }

clap = { version = "3.1", features = ["derive"] }

[workspace]
members = [
    "cfg",
    "diag",
    "name_resolve",
    "parse",
#    "type_check",
]

[profile.release]
debug = true

[profile.dev.package.parse]
opt-level = 3
