[package]
name = "yamc"
version = "0.1.0"
edition = "2021"

[dependencies]
diag = { path = "diag" }
hir = { path = "hir" }
parse = { path = "parse" }
ssir = { path = "ssir" }
tyck = { path = "tyck" }
# codegen = { path = "codegen" }

clap = { version = "3.1", features = ["derive"] }

[workspace]
members = [
#    "codegen",
    "diag",
    "hir",
    "id",
    "parse",
    "ssir",
    "tyck",
]

[profile.release]
debug = true

[profile.dev.package.parse]
opt-level = 3
