[package]
name = "parse"
version = "0.0.0"
edition = "2021"

[dependencies]
raw_diag = { path = "../raw_diag" }
lex = { path = "../lex" }
syntax = { path = "../syntax" }
text = { path = "../text" }

[dev-dependencies]
expect-test = "1.4.0"
pretty_assertions = "1.2.1"
