[package]
name = "parse"
version = "0.1.0"
edition = "2021"

[dependencies]
ast = { path = "../ast" }
diag = { path = "../diag" }
intern = { path = "../intern" }
lex = { path = "../lex" }
syntax = { path = "../syntax" }

[dev-dependencies]
expect-test = "1.4.0"
pretty_assertions = "1.2.1"
