[package]
name = "syntax"
version = "0.0.0"
edition = "2021"

[build-dependencies]
ungrammar = "1.16.1"
quote = "1.0.23"

[dependencies]
lex = { path = "../lex" }
text = { path = "../text" }

cstree = "0.11.1"
