[package]
name = "verde"
version = "0.0.0"
edition = "2021"

[dependencies]
verde-derive = { path = "derive" }

crossbeam-utils = "0.8.15"
dashmap = "5.4.0"
pin-project = "1.0.12"
rustc-hash = "1.1.0"
tokio = { version = "1.26.0", features = ["rt-multi-thread", "sync", "parking_lot"] }
