[package]
name = "verde"
version = "0.0.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[features]
serde = ["dep:serde", "dashmap/serde", "verde-derive/serde", "parking_lot/serde"]
tracing = ["dep:tracing"]

[dependencies]
verde-derive = { path = "derive" }

dashmap = "5.4.0"
parking_lot = "0.12.1"
rustc-hash = "1.1.0"
serde = { version = "1.0.156", optional = true, features = ["derive"] }
tracing = { version = "0.1.29", optional = true }
