[package]
name = "verde"
version = "0.0.0"
edition = "2021"

[package.metadata.docs.rs]
all-features = true

[features]
serde = ["dep:serde", "dashmap/serde", "verde-derive/serde"]

[dev-dependencies]
futures = "0.3.27"

[dependencies]
verde-derive = { path = "derive" }

crossbeam-utils = "0.8.15"
dashmap = "5.4.0"
pin-project = "1.0.12"
rustc-hash = "1.1.0"
serde = { version = "1.0.156", optional = true, features = ["derive"] }
tokio = { version = "1.26.0", features = ["rt-multi-thread", "sync", "parking_lot"] }
