[package]
name = "verde"
version = "0.0.0"
edition = "2021"

[dependencies]
verde-derive = { path = "derive" }

async-rwlock = "1.3.0"
crossbeam-utils = "0.8.15"
dashmap = "5.4.0"
rustc-hash = "1.1.0"
futures = { version = "0.3.26", features = ["executor", "thread-pool"] }
