[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
id = { path = "../id" }
ssir = { path = "../ssir" }

cranelift = "0.86.1"
cranelift-module = "0.86.1"
cranelift-object = "0.86.1"
target-lexicon = "0.12.4"
