[package]
name = "yamc"
version = "0.1.0"
edition = "2021"

[dependencies]
database = { path = "../common/database" }
diag = { path = "../common/diag" }
intern = { path = "../common/intern" }
parse = { path = "../syntax/parse" }

clap = { version = "3.2.17", features = ["derive"] }
tracing = "0.1.36"
tracing-forest = "0.1.4"
tracing-subscriber = { version = "0.3.15", features = ["env-filter"] }
