[package]
name = "br-lower"
version = "0.0.0"
edition = "2021"

[dependencies]
arena = { path = "../arena" }
br = { path = "../br" }
diagnostics = { path = "../diagnostics" }
syntax = { path = "../syntax" }
text = { path = "../text" }
verde = { path = "../verde" }

rustc-hash = "1.1.0"
