[package]
name = "diagnostics"
version = "0.0.0"
edition = "2021"

[dependencies]
text = { path = "../text" }
verde = { path = "../verde" }

ariadne = { workspace = true }
rustc-hash = { workspace = true }
